### ISSUE TITLE
show product names instead of multiplicators

### ISSUE THREAD

**Issue by haraldschilly** [bitcoinaustria/bitfluids#4]
below the QR codes, remove the dummy drop down lists and display some names of the respective fluids.

**Comment by apetersson** [comment]
some work towards this has already been done in 
https://github.com/apetersson/bitfluids/commit/32b0d4482b85f6526ababfb3993e57d4fc59a0ce

**Comment by haraldschilly** [comment]
ok, this is fixed and on top of apetersson's changes. everything is in master now.
